# Introduction to R 

## What is R?

R is a programming language and free software environment for statistical computing and graphics supported by the R Foundation for Statistical Computing. The R language is widely used among statisticians and data miners for developing statistical software and data analysis.

## Why R?

* R is open-source and free
* R is a powerful tool for data analysis
* R has a large and active community
* R has a large number of packages for data analysis
* R is a great tool for reproducible research

## Posit (RStudio Desktop)

Posit (formerly RStudio) is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as plotting (displaying graphs), history, debugging and workspace management tools.

:::{.callout-note}
## "R vs. RStudio"

R is the programming language, while RStudio (now Posit) is an IDE that makes it easier to write and run R code. You can use R without RStudio, but RStudio provides a user-friendly interface and additional features that make working with R more efficient.
:::

## Installing R and Posit (RStudio Desktop)

Insert a video here.

## Getting Started

```{webr-r}
print("Hello World")
```


## SQL in R


